-- 001_initial_schema.sql
-- Core tables for Kathy Koko: users, tasks, messages, calendar, email

-- User Accounts (3 Google accounts: personal, music, lyra)
CREATE TABLE IF NOT EXISTS user_accounts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  account_type VARCHAR(50) NOT NULL CHECK (account_type IN ('personal', 'music', 'lyra')),
  email VARCHAR(255) UNIQUE NOT NULL,
  display_name VARCHAR(255),
  is_primary BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Tasks (parsed from SMS with LLM validation)
CREATE TABLE IF NOT EXISTS tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  raw_text TEXT NOT NULL,
  parsed_title VARCHAR(500),
  description TEXT,
  priority VARCHAR(20) CHECK (priority IN ('urgent', 'high', 'medium', 'low')),
  category VARCHAR(100) CHECK (category IN ('lyra', 'music', 'personal', 'house')),
  status VARCHAR(50) DEFAULT 'pending' CHECK (status IN ('pending', 'clarification_needed', 'active', 'completed', 'rejected')),
  alignment_score FLOAT CHECK (alignment_score >= 0.0 AND alignment_score <= 1.0),
  pushback_reason TEXT,
  due_date TIMESTAMP,
  estimated_hours INTEGER,
  account_id UUID REFERENCES user_accounts(id),
  created_from_message_sid VARCHAR(100) UNIQUE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  completed_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);
CREATE INDEX IF NOT EXISTS idx_tasks_due_date ON tasks(due_date);
CREATE INDEX IF NOT EXISTS idx_tasks_category ON tasks(category);
CREATE INDEX IF NOT EXISTS idx_tasks_account ON tasks(account_id);

-- SMS Messages (for idempotency and conversation tracking)
CREATE TABLE IF NOT EXISTS messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  message_sid VARCHAR(100) UNIQUE NOT NULL,
  direction VARCHAR(10) NOT NULL CHECK (direction IN ('inbound', 'outbound')),
  from_number VARCHAR(20),
  to_number VARCHAR(20),
  body TEXT,
  status VARCHAR(50) CHECK (status IN ('received', 'processing', 'processed', 'failed')),
  processed_at TIMESTAMP,
  task_id UUID REFERENCES tasks(id),
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_messages_sid ON messages(message_sid);
CREATE INDEX IF NOT EXISTS idx_messages_status ON messages(status);
CREATE INDEX IF NOT EXISTS idx_messages_created ON messages(created_at DESC);

-- Calendar Events (cached from Google Calendar)
CREATE TABLE IF NOT EXISTS calendar_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  google_event_id VARCHAR(255) UNIQUE NOT NULL,
  account_id UUID REFERENCES user_accounts(id),
  calendar_id VARCHAR(255) NOT NULL,
  title VARCHAR(500),
  description TEXT,
  start_time TIMESTAMP NOT NULL,
  end_time TIMESTAMP NOT NULL,
  location TEXT,
  event_type VARCHAR(50) CHECK (event_type IN ('work', 'workout', 'studio', 'personal', 'blocked')),
  is_auto_blocked BOOLEAN DEFAULT false,
  attendees JSONB,
  recurring_rule TEXT,
  task_id UUID REFERENCES tasks(id),
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  synced_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_calendar_events_time ON calendar_events(start_time, end_time);
CREATE INDEX IF NOT EXISTS idx_calendar_events_account ON calendar_events(account_id);
CREATE INDEX IF NOT EXISTS idx_calendar_events_type ON calendar_events(event_type);
CREATE INDEX IF NOT EXISTS idx_calendar_events_google_id ON calendar_events(google_event_id);

-- Email Metadata (from Gmail)
CREATE TABLE IF NOT EXISTS emails (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  gmail_message_id VARCHAR(255) UNIQUE NOT NULL,
  gmail_thread_id VARCHAR(255),
  account_id UUID REFERENCES user_accounts(id),
  from_address VARCHAR(255),
  to_addresses TEXT[],
  cc_addresses TEXT[],
  subject VARCHAR(500),
  snippet TEXT,
  body_preview TEXT,
  labels TEXT[],
  is_urgent BOOLEAN DEFAULT false,
  urgency_reason TEXT,
  is_read BOOLEAN DEFAULT false,
  has_draft BOOLEAN DEFAULT false,
  draft_id UUID,
  received_at TIMESTAMP,
  flagged_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_emails_account ON emails(account_id);
CREATE INDEX IF NOT EXISTS idx_emails_urgent ON emails(is_urgent);
CREATE INDEX IF NOT EXISTS idx_emails_received ON emails(received_at DESC);
CREATE INDEX IF NOT EXISTS idx_emails_gmail_id ON emails(gmail_message_id);

-- Email Drafts (generated by Ghostwriter)
CREATE TABLE IF NOT EXISTS email_drafts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email_id UUID REFERENCES emails(id),
  persona VARCHAR(50) NOT NULL CHECK (persona IN ('lyra', 'music', 'contractor')),
  subject VARCHAR(500),
  body TEXT NOT NULL,
  tone_notes TEXT,
  status VARCHAR(50) DEFAULT 'draft' CHECK (status IN ('draft', 'approved', 'sent', 'rejected')),
  sent_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_email_drafts_status ON email_drafts(status);
CREATE INDEX IF NOT EXISTS idx_email_drafts_email ON email_drafts(email_id);

-- Update timestamp trigger function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply update timestamp triggers
CREATE TRIGGER update_user_accounts_updated_at BEFORE UPDATE ON user_accounts
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_tasks_updated_at BEFORE UPDATE ON tasks
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_calendar_events_updated_at BEFORE UPDATE ON calendar_events
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_emails_updated_at BEFORE UPDATE ON emails
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_email_drafts_updated_at BEFORE UPDATE ON email_drafts
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
